notifications:
  email:
    recipients: invictus86@gmail.com
    on_success: always
    on_failure: always

language: cpp

matrix:
  include:
    # Bionic Ubuntu 18.04
    - os: linux
      name: "Bionic - gcc"
      dist: bionic # We can't install packages on Bionic, not sure why. Travis ignores addons...
      compiler: gcc

    # Bionic Ubuntu 18.04
    

    - os: windows

before_install:
  # Override compilers set by Travis
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ ! -z "${USE_CC}" ]; then echo "Override CC=${USE_CC}"; eval "CC=${USE_CC}"; fi
      if [ ! -z "${USE_CXX}" ]; then echo "Override CXX=${USE_CXX}"; eval "CXX=${USE_CXX}"; fi
      echo ${CC} && ${CC} --version
      echo ${CXX} && ${CXX} --version
    fi  

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################

  # Make a dir for all
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  # Install a recent CMake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.16/cmake-3.16.3-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

  # Go back to ${TRAVIS_BUILD_DIR}
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - cmake --build . --config Release
  - ctest

