notifications:
  email:
    recipients: invictus86@gmail.com
    on_success: always
    on_failure: always

language: cpp

matrix:
  include:
    # Bionic Ubuntu 18.04
    - os: linux
      name: "Bionic - gcc"
      dist: bionic # We can't install packages on Bionic, not sure why. Travis ignores addons...
      compiler: gcc

    # Bionic Ubuntu 18.04
    - os: linux
      name: "Bionic - clang"
      dist: bionic # We can't install packages on Bionic, not sure why. Travis ignores addons...
      compiler: clang

    # clang-6
    - os: linux
      name: "Xenial - clang 6"
      dist: xenial
      env: [USE_CC='/usr/bin/clang-6.0', USE_CXX='/usr/bin/clang++-6.0']
      addons:
        apt:
          packages: ['clang-6.0', 'cmake']
          sources: ['ubuntu-toolchain-r-test']

    # clang-7
    - os: linux
      name: "Xenial - clang 7"
      dist: xenial
      env: [USE_CC='/usr/bin/clang-7', USE_CXX='/usr/bin/clang++-7']
      addons:
        apt:
          packages: ['clang-7', 'cmake']
          sources: ['llvm-toolchain-xenial-7']

    # clang-8
    - os: linux
      name: "Xenial - clang 8"
      dist: xenial
      env: [USE_CC='/usr/bin/clang-8', USE_CXX='/usr/bin/clang++-8']
      addons:
        apt:
          packages: ['clang-8', 'cmake']
          sources: ['llvm-toolchain-xenial-8']

    # gcc-7
    - os: linux
      name: "Xenial - gcc 7"
      dist: xenial
      env: [USE_CC='/usr/bin/gcc-7', USE_CXX='/usr/bin/g++-7']
      addons:
        apt:
          packages: ['gcc-7', 'g++-7', 'cmake']
          sources: ['ubuntu-toolchain-r-test']

    # gcc-8
    - os: linux
      name: "Xenial - gcc 8"
      dist: xenial
      env: [USE_CC='/usr/bin/gcc-8', USE_CXX='/usr/bin/g++-8']
      addons:
        apt:
          packages: ['gcc-8', 'g++-8', 'cmake']
          sources: ['ubuntu-toolchain-r-test']

    # gcc-9
    - os: linux
      name: "Xenial - gcc 9"
      dist: xenial
      env: [USE_CC='/usr/bin/gcc-9', USE_CXX='/usr/bin/g++-9']
      addons:
        apt:
          packages: ['gcc-9', 'g++-9', 'cmake']
          sources: ['ubuntu-toolchain-r-test']

    - os: osx
      osx_image: xcode9.4
      compiler: clang

    - os: osx
      osx_image: xcode10.2
      compiler: clang

    - os: windows

before_install:
  # Override compilers set by Travis
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ ! -z "${USE_CC}" ]; then echo "Override CC=${USE_CC}"; eval "CC=${USE_CC}"; fi
      if [ ! -z "${USE_CXX}" ]; then echo "Override CXX=${USE_CXX}"; eval "CXX=${USE_CXX}"; fi
      echo ${CC} && ${CC} --version
      echo ${CXX} && ${CXX} --version
    fi  

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################

  # Make a dir for all
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  # Install a recent CMake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.16/cmake-3.16.3-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

  # Go back to ${TRAVIS_BUILD_DIR}
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - cmake --build . --config Release
  - ctest -C Release

